CAM_WIDTH : 640
CAM_HEIGHT : 480
WEIGHT : test_v8n_230927.pt
# WEIGHT : yolov8n.pt
SCREEN_WIDTH : 960 
SCREEN_HEIGHT : 600
API_PORT : 21560
API_IP : 192.168.0.210
WINDOWED : true
BKG_CAM : false
CONF_THRESHOLD : 0.5
DISPLAY_DETECTION_TEXT : false
DISPLAY_DETECTION_BOX : true
TITLE : Vision AI Helper 시스템




